# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ustomer.proto\x12\x04\x64\x65mo\";\n\x08\x43ustomer\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tfirstName\x18\x02 \x02(\t\x12\x10\n\x08lastName\x18\x03 \x02(\t\"-\n\tCustomers\x12 \n\x08\x63ustomer\x18\x01 \x03(\x0b\x32\x0e.demo.CustomerB\"\n\x10tk.tinkerit.demoB\x0e\x43ustomerProtos')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'customer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\020tk.tinkerit.demoB\016CustomerProtos'
  _globals['_CUSTOMER']._serialized_start=24
  _globals['_CUSTOMER']._serialized_end=83
  _globals['_CUSTOMERS']._serialized_start=85
  _globals['_CUSTOMERS']._serialized_end=130
# @@protoc_insertion_point(module_scope)
